### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by gitboy16** [grasph/wrapit#12]
Hi,
Is there a plan to support windows?
Thanks

**Comment by grasph** [comment]
Hello @gitboy16 ,

There are currently no plan for a support for Windows, although nothing should prevent building the tool on Windows. Pull request to fix portability issue are welcome.

The code generated by WrapIt is expected to be portable, although I've never tried to compile it on Windows.

Cheers,
Philippe.

**Comment by gitboy16** [comment]
Here is the error message when I try to build it
```
C:\home\wrapit\build>cmake ..
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19044.
-- The C compiler identification is MSVC 19.23.28105.4
-- The CXX compiler identification is MSVC 19.23.28105.4
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.23.28105/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.23.28105/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:22 (find_package):
  Could not find a package configuration file provided by "Clang" with any of
  the following names:

    ClangConfig.cmake
    clang-config.cmake

  Add the installation prefix of "Clang" to CMAKE_PREFIX_PATH or set
  "Clang_DIR" to a directory containing one of the above files.  If "Clang"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "C:/home/wrapit/build/CMakeFiles/CMakeOutput.log".
```

**Comment by grasph** [comment]
Do you have LLVM and Clang installed (https://llvm.org/docs/GettingStartedVS.html) and do you have a `ClangConfig.cmake` or `clang-config.cmake` file in the installed software?

You need to specify the path to this file to `cmake` with the option `-DClang_DIR=...`  as indicated in the error message you get.

Philippe.

**Comment by gitboy16** [comment]
Yes I have llvm installed. I installed it from:
https://github.com/mstorsjo/llvm-mingw
As they provide portable version. I just have to include llvm\bin to PATH and it works well. However I was unable to find any `ClangConfig.cmake` or `clang-config.cmake` file.
Is there a copy of these files somewhere? Thank you.
