### ISSUE TITLE
`dlopen` fails

### ISSUE THREAD

**Issue by t-bltg** [grasph/wrapit#18]
I'm wrapping a c++ library and `dlopen`ing the resulting shared library fails:

The following patch seems to fix it:
```diff
diff --git a/src/CodeTree.cpp b/src/CodeTree.cpp
index e7c2054..15be57d 100644
--- a/src/CodeTree.cpp
+++ b/src/CodeTree.cpp
@@ -804,7 +804,7 @@ std::ostream& CodeTree::generate_jl(std::ostream& o,

   o <<  "\n"
     "using CxxWrap\n"
-    "@wrapmodule(\"" << shared_lib_basename<< "\")\n"
+    "@wrapmodule(joinpath(@__DIR__, \"" << shared_lib_basename<< "\"))\n"
     "\n"
     "function __init__()\n"
     "    @initcxx\n"
```

Would it be acceptable or should we configure the shared library prefix in the `toml` configuration file ?

**Comment by grasph** [comment]
Did you try to include the directory that contains your shared library in your JULIA_LOAD_PATH  as done in the different examples (see the setup.sh file) ?

**Comment by t-bltg** [comment]
Yes, I know about `JULIA_LOAD_PATH`, the point being wouldn't it be nice to provide a configurable way (via `toml` file) to avoid using environment variables ?

If the built shared library resides along the generated `<module_name>.jl`, I'd expect the module to `dlopen` the shared library automatically without having to populate `JULIA_LOAD_PATH` ...

**Comment by t-bltg** [comment]
Also, `JULIA_LOAD_PATH` has no effect on this.

You have to use `LD_LIBRARY_PATH=$(pwd)` instead, and anyone knows that this shouldn't be recommended.

I really think there should be a configurable option that uses `@__DIR__` by default (creating an absolute path), but can be set to a relative path as before for retro-compatibility.
