### ISSUE TITLE
Add CI to run the unit tests

### ISSUE THREAD

**Issue by grasph** [grasph/wrapit#45]
This issue is opened to follow the project of a code validation using GitHub  actions.

Code validation is currently done by hand before pushing the code to Github, using the `test/runtest.jl` script. The project aims to have it run automatically.

The CI will need to compile the code and run the runtest.jl script, which uses the unit tests and the examples for the validation.

Validation should be run with Linux and Mac OS on x64 architecture.

Example that can be useful as a reference: https://github.com/JuliaInterop/libcxxwrap-julia

New BinaryBuilder recipe: https://github.com/JuliaPackaging/Yggdrasil/pull/7798
Package to instantiate build from BinaryBuiler:  https://github.com/grasph/wrapit.jl

**Comment by graeme-a-stewart** [comment]
Thanks @grasph - I can work on it.I think you need to invite me as a developer to the project in order to be able to assign the issue to me.

**Comment by rajkumardongre** [comment]
is  this issue still open?

**Comment by grasph** [comment]
Yes, it is. I don't know if @graeme-a-stewart has started working on it.

**Comment by graeme-a-stewart** [comment]
No, sorry - I have unfortunately been very busy with other things recently. But it is still on my TODO list.

**Comment by grasph** [comment]
Done with commit [4e5dc](https://github.com/grasph/wrapit/commit/4e5dc344961584768c410a470fd9870275e52fa4).
