### ISSUE TITLE
Ignoring 'out_jl_dir' in configuration file 

### ISSUE THREAD

**Issue by peremato** [grasph/wrapit#53]
If I set `out_jl_dir   = "jl"` in the configuration file, the Julia generated files are put in `jl/src`. I think if the configuration parameter is set, then it should be honoured.

**Comment by grasph** [comment]
It is not ignored. The parameter sets the directory for the generated Julia module. The  julia code is put in `src` subdirectory following common practice.

PR #58 adds a parameter to allow changing the subdirectory name or getting the .jl file directory in the module directory.
